#!/bin/bash

cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_1.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_1.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_2.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_2.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_3.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_3.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_4.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_4.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_5.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_5.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_6.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_6.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_7.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_7.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_8.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_8.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_9.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_9.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_10.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_10.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_11.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_11.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_12.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_12.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_13.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_13.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_14.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_14.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_15.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_15.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_16.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_16.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_17.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_17.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_18.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_18.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_19.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_19.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_20.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_20.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_21.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_21.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_22.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_22.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_23.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_23.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_24.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_24.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_25.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_25.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_26.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_26.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_27.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_27.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_28.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_28.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_29.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_29.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_30.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_30.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_31.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_31.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_32.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_32.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_33.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_33.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_34.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_34.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_35.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_35.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_36.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_36.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_37.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_37.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_38.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_38.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_39.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_39.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_40.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_40.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::UsbSerial_41.xml /linuxcash/cash/conf/drivers/
cp -f --force /opt/FirstHelpAndScan/driverssource/hw::DatalogicScanner_41.xml /linuxcash/cash/conf/drivers/
